GET http://localhost:8080/api/v1/opening

###
POST http://localhost:8080/api/v1/opening
Content-Type: application/json

{
    "role": "Software Engineer",
    "company": "Google",
    "location": "Mountain View, CA",
    "Link": "http://www.google.com",
    "salary": 100000,
    "remote": true
}

###
GET http://localhost:8080/api/v1/openings 

###
PUT http://localhost:8080/api/v1/opening

###
DELETE  http://localhost:8080/api/v1/opening