POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
    "name": "Jose Doe",
    "login": "jose@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8080/api/v1/users

###
GET http://localhost:8080/api/v1/user/1

###
PUT http://localhost:8080/api/v1/user/1
Content-Type: application/json

{
    "name": "John Doe",
    "login": "jon@gmail.com",
    "password": "123456"
}

###
DELETE http://localhost:8080/api/v1/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDQ5Mzg4NzYsImxvZ2luIjoiam9uQGdtYWlsLmNvbSJ9.-JJQXrUAE9t_P6INe1cp8-IXdzReaw0lpuBYebkFsNg
